// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edvuehwrxzjltvtmqesl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkdnVlaHdyeHpqbHR2dG1xZXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTUwNjIsImV4cCI6MjA3MzY5MTA2Mn0.oTQtLglqJBivK0t6-cYYR-iGFeEvT_FwkCd9wkwc1hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});